name: Build Go binaries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: |
          mkdir -p build
          go build -o build/git-ingest-local-${{ matrix.os }} .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-ingest-local-${{ matrix.os }}
          path: build/
