name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/git-ingest-local-linux .
          GOOS=darwin  GOARCH=arm64 go build -o dist/git-ingest-local-macos .
          GOOS=windows GOARCH=amd64 go build -o dist/git-ingest-local-windows.exe .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
